# Generated by Django 3.1.7 on 2023-11-13 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
