# Generated by Django 3.1.7 on 2023-11-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_created',
        ),
    ]
